# Generated by Django 4.1 on 2023-07-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_article_size'),
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Order',
            new_name='ArticleOrder',
        ),
    ]
