# Generated by Django 4.1 on 2023-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_alter_user_pw_alter_user_pwc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
