# Generated by Django 4.1 on 2023-08-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleorder',
            old_name='command',
            new_name='order',
        ),
    ]
