# Generated by Django 4.1 on 2023-08-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_rename_command_articleorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleorder',
            old_name='quantity',
            new_name='total',
        ),
    ]
