# Generated by Django 4.1 on 2023-08-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0006_rename_quantity_articleorder_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='command',
            new_name='customer',
        ),
    ]
