# Generated by Django 4.1 on 2023-08-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0007_rename_command_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleorder',
            old_name='total',
            new_name='quantity',
        ),
    ]
