# Generated by Django 4.2.3 on 2023-08-28 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("livraison", "0008_rename_total_articleorder_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tel",
        ),
        migrations.AddField(
            model_name="customer",
            name="User_Customer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="tel",
            field=models.BigIntegerField(default=False),
        ),
    ]
