# Generated by Django 4.1 on 2023-07-22 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('store', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('telephone', models.BigIntegerField(verbose_name='+237')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'db_table': 'supplier',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('Quantity', models.BigIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='supplier_category', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ['reference'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('color', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=10)),
                ('price', models.BigIntegerField(verbose_name='FCFA')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('a', 'Available'), ('ua', 'Unavailable')], default='a', max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_article', to='stock.category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'db_table': 'article',
                'ordering': ['-added'],
                'managed': True,
            },
        ),
    ]
