# Generated by Django 4.1 on 2023-07-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
