# Generated by Django 4.1 on 2023-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.BigIntegerField(default=False),
        ),
    ]
