# Generated by Django 4.1 on 2023-07-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_category', to='stock.supplier'),
        ),
    ]
