# Generated by Django 4.1 on 2023-07-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_category_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_article', to='stock.supplier'),
        ),
    ]
