# Generated by Django 4.1 on 2023-07-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_supplier_article_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
    ]
