# Generated by Django 4.1 on 2023-07-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_article_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='supplier',
        ),
    ]
