# Generated by Django 4.1 on 2023-07-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_article_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True, 'ordering': ['nam'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='nam',
        ),
    ]
