# Generated by Django 4.1 on 2023-07-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_supplier_options_rename_name_supplier_nam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nam',
            new_name='name',
        ),
    ]
