# Generated by Django 4.1 on 2023-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_supplier_options_rename_nam_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='size',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
