# Generated by Django 4.1 on 2023-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_article_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
