# Generated by Django 4.2.3 on 2023-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0019_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(default=False, upload_to="image"),
        ),
    ]
