# Generated by Django 4.1 on 2023-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
    ]
