# Generated by Django 4.1 on 2023-08-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_article_added_alter_category_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='size',
        ),
    ]
